import { CallModal } from "@/components/widgets/CallModal/CallModal";
import { Header } from "@/components/layout/Header/Header";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sem Pro Group",
  description: "Generated by create next app",
  icons: {
    icon: "/imgs/secondary/house.webp",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <CallModal />
        {children}
      </body>
    </html>
  );
}
